### ISSUE TITLE
File Selection with prefix not ending in * throws IndexError

### ISSUE THREAD

**Issue by cboyce93** [cboyce93/2CANN#2]
Error occurs when prefix added with input not ending in wildcard i.e., ${ROOT}/*/<p_>*.py of the SOE and IOE windows.

Traceback (most recent call last):
  File "/home/cboyce/git/2CANN/handlers.py", line 350, in on_soe_view_file_selection_button_clicked
    list_file_selection_contents(self.builder, self.project.vars, fs, ftype)
  File "/home/cboyce/git/2CANN/util/file_selection.py", line 35, in list_file_selection_contents
    concat_fs.append(concatenate(fp, fs_arr))
  File "/home/cboyce/git/2CANN/util/file_selection.py", line 60, in concatenate
    arr = remove_wildcards(fp, arr)
  File "/home/cboyce/git/2CANN/util/file_selection.py", line 85, in remove_wildcards
    fs_arr[0] = m[0]
IndexError: list index out of range

**Comment by cboyce93** [comment]
fp was empty string at the last index of the stdout.split array. In case of terminating \n we now check for empty string: if fp != '' before making the call

for fp in stdout.split("\n"):
                if fp != '':
                    concat_fs.append(concatenate(fp, fs_arr))
